<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>UnlimitedIncubatorHatches</AssemblyName>
        <RootNamespace>UnlimitedIncubatorHatches</RootNamespace>
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Library</OutputType>
        <Platforms>AnyCPU</Platforms>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.*" />
    </ItemGroup>
</Project>
